# Generated by Django 5.1.1 on 2024-10-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simcard',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='simcard',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
